//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEFDatabaseFirst
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CableTVEntities : DbContext
    {
        public CableTVEntities()
            : base("name=CableTVEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<CableTVProblem> CableTVProblems { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Master> Masters { get; set; }
        public virtual DbSet<OrderOnCableTV> OrderOnCableTVs { get; set; }
        public virtual DbSet<OrderRepairAndRestruction> OrderRepairAndRestructions { get; set; }
        public virtual DbSet<Street> Streets { get; set; }
        public virtual DbSet<SubscriberRelationship> SubscriberRelationships { get; set; }
        public virtual DbSet<Subscriber> Subscribers { get; set; }
        public virtual DbSet<UserAction> UserActions { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<View_City_Test> View_City_Test { get; set; }
    
        public virtual int Test_Procedure_Name(ObjectParameter countCity)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Test_Procedure_Name", countCity);
        }
    }
}
