//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEFDatabaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderOnCableTV
    {
        public int Id { get; set; }
        public int SubscriberId { get; set; }
        public string UserLocation { get; set; }
        public string PhoneNumber { get; set; }
        public string Remark { get; set; }
        public Nullable<int> CableTVProblemId { get; set; }
        public string NonStandardProblem { get; set; }
        public Nullable<int> MasterId { get; set; }
        public byte OrderStatus { get; set; }
        public Nullable<System.DateTime> ExecutionDate { get; set; }
        public Nullable<System.DateTime> CallbackDate { get; set; }
        public bool IsCollectiveOrder { get; set; }
        public System.DateTime CreationDate { get; set; }
        public System.DateTime EstimatedCompletionDate { get; set; }
    
        public virtual CableTVProblem CableTVProblem { get; set; }
        public virtual Master Master { get; set; }
        public virtual Subscriber Subscriber { get; set; }
    }
}
