//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEFDatabaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderRepairAndRestruction
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public Nullable<int> ResponsibleMasterId { get; set; }
        public Nullable<int> MasterPerformerId { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> StreetId { get; set; }
        public string HouseNumber { get; set; }
        public string ApartmentNumber { get; set; }
        public string Problem { get; set; }
        public string Remark { get; set; }
        public byte Status { get; set; }
        public System.DateTime DateOfExecution { get; set; }
        public System.DateTime DateOfCallback { get; set; }
        public System.DateTime DateOfCreation { get; set; }
        public System.DateTime EstimatedCompletionDate { get; set; }
    
        public virtual City City { get; set; }
        public virtual Master Master { get; set; }
        public virtual Master Master1 { get; set; }
        public virtual Street Street { get; set; }
        public virtual User User { get; set; }
    }
}
